### ISSUE TITLE
Could you please expose "summary" info as a json api?

### ISSUE THREAD

**Issue by shawyunz** [simeonmiteff/nzcovid19cases#1]
Thanks for your repo, I wonder if could add some header info from the official website.

On top of the website:
https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-current-cases
> Summary
> Number of confirmed and probable cases in New Zealand - 155
> Number of recovered cases – 12
> Number of community transmission cases – 4

IMHO, at least two fields like "type and number" are enough, and could also be used to calculate some other amount.

Cheers

**Comment by simeonmiteff** [comment]
@shawyunz like this?

https://nzcovid19api.xerra.nz/casestats/json

https://github.com/simeonmiteff/nzcovid19cases/commit/76637ec4a3d4e9929e5152a866f2f3039dd43048
