### ISSUE TITLE
Also scrape timestamps from all tables scraped from MOH

### ISSUE THREAD

**Issue by simeonmiteff** [simeonmiteff/nzcovid19cases#10]
MOH has begun adding text indicating when pages and tables are updated. Scrape them also and include them in the API and metrics.

**Comment by shawyunz** [comment]
Looking forward to this feature. This is what I was thinking about, but haven't reached that point for my app. (btw hope not affects the original apis)

**Comment by shawyunz** [comment]
Or is it possible to monitor the API to see when the data changes?
e.g: for my app, it is the timestamps when your API updated, not the timestamps MOH publish something.

**Comment by simeonmiteff** [comment]
@shawyunz as with my response to the other issue - I recommend pulling the arcgis.com JSON layers, as now described in [the README](README.md). Cheers!
