### ISSUE TITLE
[feature request] More details from "Total cases by DHB"

### ISSUE THREAD

**Issue by shawyunz** [simeonmiteff/nzcovid19cases#11]
MOH has "Active", "Recovered" and some more columns in the table "Total cases by DHB".
Would you consider to add those columns into API? 
Cheers.

**Comment by simeonmiteff** [comment]
@shawyunz - I have removed the cases and locations (cases by DHB - which I was computing from cases directly, and not scraping). I have updated [the README](README.md) with information about why, and alternative data sources. I would recommend looking into the arcgis.com layers...

Sorry :-(
