### ISSUE TITLE
Active cases being read in as deaths

### ISSUE THREAD

**Issue by jamescmacey** [simeonmiteff/nzcovid19cases#12]

**Comment by jamescmacey** [comment]
Accidentally pressed enter before typing description - here's the API output from /casestats/json:
```JSON
{
  "ConfirmedCasesTotal": 1154,
  "ConfirmedCasesNew24h": 0,
  "ProbableCasesTotal": 350,
  "ProbableCasesNew24h": 0,
  "RecoveredCasesTotal": 1456,
  "RecoveredCasesNew24h": 1,
  "DeathCasesTotal": 27,
  "DeathCasesNew24h": -1
}
```

And here's the MOH table:
![table](https://user-images.githubusercontent.com/10700494/82746016-32933f00-9ddf-11ea-99d7-e3f01cb29928.PNG)

**Comment by simeonmiteff** [comment]
Hi @jamescmacey. Sorry, this is "a bit shit" but I'm closing this because I'm retiring the project. Please feel free to fork this repo to continue development.
