### ISSUE TITLE
Temporal data?

### ISSUE THREAD

**Issue by neon-ninja** [simeonmiteff/nzcovid19cases#2]
Hi,

Thanks for making your repo open source and thanks for providing this API. I think it might be interesting to add in which day each case was reported, this might be useful for building plots of cases over time, or timeline maps (such as https://public.tableau.com/views/coivd-nzmap/Dashboard1?:embed=y&:embed_code_version=3&:loadOrderID=1&:display_count=y&:origin=viz_share_link). While MOH don't have a "date reported" column on their site, we can correlate the case numbers with the days/case numbers on https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv - e.g.

Case 1 was reported on 2/28/20
Cases 2-3 were reported on 3/4/20
Case 4 was reported on 3/6/20

and so on. These dates could be added as properties to the geojson, or as a column to the csv.

**Comment by simeonmiteff** [comment]
@neon-ninja very good timing - I got another request today, from a researcher needing a date column. I've taken a first stab at this in a Google Sheet that I have set up to pull the CSV API periodically, see the right-most columns in the "DATA" tab: 

https://docs.google.com/spreadsheets/d/1NJiDg2z7Y79RUkQ-a648fFD_EmziztYLLkQW_FOrLGo/edit#gid=576672848

I had already manually added the more recent dates, but needed a source for the cases reported last week, which I found in the second link you posted - so thank you!

I'm not sure yet whether it is worth adding a persistent data store to the API service and joining records scraped from MOH with that automatically. Someone else is working on a standard data format (an SQL schema) that (I hope) MOH will adopt, in which case they might add a date column, and perhaps also make the whole scraping/normalisation thing unnecessary.

Please let me know what you think.

**Comment by neon-ninja** [comment]
Nice. It's up to you where you want to draw the line - otherwise before you know it you'll be adding things like census stats for each affected location. It's fairly trivial to do the join at the application level.

**Comment by neon-ninja** [comment]
I think you might have an issue with the M/D/Y parsing though - some cases are classified as April - 2020-04-01 for example

**Comment by simeonmiteff** [comment]
@neon-ninja good catch. I think it is right now, however it looks like this effort may overtake mine with much better data quality: https://github.com/nzherald/nz-covid19-data

I think I read a comment in one of their repo's issues that they're planning to add reported date.

**Comment by shawyunz** [comment]
> @neon-ninja good catch. I think it is right now, however it looks like this effort may overtake mine with much better data quality: https://github.com/nzherald/nz-covid19-data
> 
> I think I read a comment in one of their repo's issues that they're planning to add reported date.

well, but no JSON there? (I bet really annoying when the format of the source has been changed)

**Comment by simeonmiteff** [comment]
@neon-ninja note that MOH has added date columns, and the API now exposes these.
