### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by neon-ninja** [simeonmiteff/nzcovid19cases#3]
`Access to XMLHttpRequest at 'https://nzcovid19api.xerra.nz/cases/geojson' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` - could you please add an "Access-Control-Allow-Origin: *" header to your nginx server? This might be useful - https://enable-cors.org/server_nginx.html

**Comment by simeonmiteff** [comment]
@neon-ninja thanks for the bug report. Please check if it is working as expected now...

```
simeon@feijoa:~$ curl -v https://nzcovid19api.xerra.nz/alertlevel/json 2>&1 | grep '^<'
< HTTP/2 200 
< server: nginx/1.15.6
< date: Wed, 25 Mar 2020 05:42:16 GMT
< content-type: text/plain; charset=utf-8
< content-length: 43
< access-control-allow-origin: *
< strict-transport-security: max-age=15724800; includeSubDomains
```

**Comment by neon-ninja** [comment]
Thanks, that works
