### ISSUE TITLE
[feature request]Would you consider to add this one "clusters"

### ISSUE THREAD

**Issue by shawyunz** [simeonmiteff/nzcovid19cases#4]
The source link is: https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-current-situation/covid-19-current-cases/covid-19-clusters

(Btw, the format of data was changing so frequently, nice work.)

**Comment by simeonmiteff** [comment]
@shawyunz implemented in 08992a6

Also available here:
- https://nzcovid19api.xerra.nz/clusters/json
- https://nzcovid19api.xerra.nz/clusters/csv
